name: Build and deploy Laravel API to Azure Web App - dsusite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare Laravel app
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Prepare deployment package
        run: |
          mkdir deploy

          # Copy Laravel structure
          cp -r public/* deploy/                          # Front controller to root
          cp -r app bootstrap config database resources routes storage deploy/
          cp artisan composer.* .env deploy/
          cp -r vendor deploy/

          # Fix Laravel public path
          sed -i "s|__DIR__\.'/../|__DIR__\.'/|g" deploy/index.php

          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-api
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-api

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0D9E88B12544313B84B4F71570507DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7039930660943B2A0F6D590350E39DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8ACD6D8409004D04B49D4A2B5C9DB734 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'dsusite'
          slot-name: 'Production'
          package: .
